language: php

# lock distro so new future defaults will not break the build
dist: trusty

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm-3.18
  allow_failures:
    - php: hhvm-3.18

install:
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text
